name: Update Discounts

on:
  schedule:
    - cron: '0 */6 * * *' # Запускать каждые 6 часов
  workflow_dispatch: # Возможность запустить вручную кнопкой

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 # Добавь свои библиотеки

      - name: Run Parser
        run: python parser/main.py # Путь к твоему скрипту

      - name: Commit and Push if changed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update discounts data" && git push)
